- hosts: localhost
  connection: local
  vars:
    resource_group: "rg-devops-integrador"
    cluster_name: "aks-integrador"

  tasks:
    - name: Crear carpeta de keyrings
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar clave GPG correcta de Kubernetes
      become: yes
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | \
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Añadir repositorio de Kubernetes
      become: yes
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: Actualizar cache apt
      become: yes
      apt:
        update_cache: yes

    - name: Instalar kubectl
      become: yes
      apt:
        name: kubectl
        state: present

    - name: Obtener credenciales de AKS
      command: >
        az aks get-credentials
        --resource-group {{ resource_group }}
        --name {{ cluster_name }}
        --overwrite-existing
      changed_when: false

    - name: Verificar conexión con el clúster
      command: kubectl get nodes
      register: nodes_out

    - name: Mostrar nodos detectados
      debug:
        msg: "{{ nodes_out.stdout_lines }}"

    - name: Instalar librería kubernetes de Python
      become: yes
      apt:
        name: python3-kubernetes
        state: present

    - name: Crear ConfigMap para la App Rick-Morty
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: rick-morty-config
            namespace: default
          data:
            API_URL: "https://rickandmortyapi.com/api"
            NODE_ENV: "production"
